"""initial_schema

Revision ID: 150398c7aded
Revises: 
Create Date: 2026-02-27 17:48:23.701550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '150398c7aded'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('chat_history', sa.Column('session_id', sa.Integer(), nullable=True, comment='Which conversation session this message belongs to'))
    op.create_foreign_key(None, 'chat_history', 'chat_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_history', type_='foreignkey')
    op.drop_column('chat_history', 'session_id')
    # ### end Alembic commands ###
