"""add password_hash to the user table

Revision ID: 4a1dcd193814
Revises: d0d28cd50e50
Create Date: 2026-02-25 13:59:38.775033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a1dcd193814'
down_revision: Union[str, Sequence[str], None] = 'd0d28cd50e50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), server_default='', nullable=False, comment='Hashed password for authentication'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
