"""add issue_id to escalation_rules

Revision ID: 8e533b75d0e1
Revises: 
Create Date: 2026-02-20 14:43:08.631100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e533b75d0e1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('escalation_rules', sa.Column('issue_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'escalation_rules', 'issues', ['issue_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'escalation_rules', type_='foreignkey')
    op.drop_column('escalation_rules', 'issue_id')
    # ### end Alembic commands ###
