"""update escalation_rules schema and added escalation table

Revision ID: d0d28cd50e50
Revises: 8e533b75d0e1
Create Date: 2026-02-20 15:45:13.822349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd0d28cd50e50'
down_revision: Union[str, Sequence[str], None] = '8e533b75d0e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('escalation_rules', 'priority',
               existing_type=postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', name='priority_enum'),
               comment=None,
               existing_comment='Which issue priority this rule applies to',
               existing_nullable=False)
    op.alter_column('escalation_rules', 'max_call_attempts',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Number of missed calls before escalation triggers',
               existing_nullable=False)
    op.alter_column('escalation_rules', 'max_time_without_response',
               existing_type=postgresql.INTERVAL(),
               comment=None,
               existing_comment="Time duration (e.g., '02:00:00') before escalation triggers",
               existing_nullable=False)
    op.alter_column('escalation_rules', 'escalate_to_role',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='manager | supervisor | admin — who receives the alert',
               existing_nullable=False)
    op.drop_constraint(op.f('escalation_rules_issue_id_fkey'), 'escalation_rules', type_='foreignkey')
    op.drop_column('escalation_rules', 'issue_id')
    op.alter_column('issue_assignments', 'issue_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Which issue is being assigned',
               existing_nullable=False)
    op.alter_column('issue_assignments', 'assigned_to_solver_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Problem solver who must fix it',
               existing_nullable=False)
    op.alter_column('issue_assignments', 'assigned_by_supervisor_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Supervisor who assigned (or system user)',
               existing_nullable=False)
    op.alter_column('issue_assignments', 'due_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Copied from issues.deadline_at',
               existing_nullable=True)
    op.alter_column('issue_assignments', 'status',
               existing_type=postgresql.ENUM('ACTIVE', 'COMPLETED', 'REOPENED', name='assignment_status_enum'),
               comment=None,
               existing_comment='ACTIVE | COMPLETED | REOPENED',
               existing_nullable=False)
    op.alter_column('issues', 'site_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Which facility site the issue belongs to',
               existing_nullable=False)
    op.alter_column('issues', 'raised_by_supervisor_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Supervisor who reported the issue',
               existing_nullable=False)
    op.alter_column('issues', 'title',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='Short problem description (AI-generated, max 50 chars preferred)',
               existing_nullable=False)
    op.alter_column('issues', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Detailed problem explanation from AI extraction',
               existing_nullable=False)
    op.alter_column('issues', 'priority',
               existing_type=postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', name='priority_enum'),
               comment=None,
               existing_comment='low | medium | high — set by AI from urgency keywords',
               existing_nullable=False)
    op.alter_column('issues', 'deadline_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Calculated: created_at + days_to_fix from AI extraction',
               existing_nullable=True)
    op.alter_column('issues', 'status',
               existing_type=postgresql.ENUM('OPEN', 'ASSIGNED', 'IN_PROGRESS', 'RESOLVED_PENDING_REVIEW', 'COMPLETED', 'REOPENED', 'ESCALATED', name='issue_status_enum'),
               comment=None,
               existing_comment='Lifecycle: OPEN → ASSIGNED → IN_PROGRESS → RESOLVED_PENDING_REVIEW → COMPLETED',
               existing_nullable=False)
    op.alter_column('issues', 'track_status',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Additional tracking: awaiting_solver, in_progress, awaiting_review, resolved',
               existing_nullable=True)
    op.alter_column('issues', 'latitude',
               existing_type=sa.NUMERIC(precision=10, scale=8),
               comment=None,
               existing_comment='Issue GPS latitude',
               existing_nullable=True)
    op.alter_column('issues', 'longitude',
               existing_type=sa.NUMERIC(precision=11, scale=8),
               comment=None,
               existing_comment='Issue GPS longitude',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('issues', 'longitude',
               existing_type=sa.NUMERIC(precision=11, scale=8),
               comment='Issue GPS longitude',
               existing_nullable=True)
    op.alter_column('issues', 'latitude',
               existing_type=sa.NUMERIC(precision=10, scale=8),
               comment='Issue GPS latitude',
               existing_nullable=True)
    op.alter_column('issues', 'track_status',
               existing_type=sa.VARCHAR(length=100),
               comment='Additional tracking: awaiting_solver, in_progress, awaiting_review, resolved',
               existing_nullable=True)
    op.alter_column('issues', 'status',
               existing_type=postgresql.ENUM('OPEN', 'ASSIGNED', 'IN_PROGRESS', 'RESOLVED_PENDING_REVIEW', 'COMPLETED', 'REOPENED', 'ESCALATED', name='issue_status_enum'),
               comment='Lifecycle: OPEN → ASSIGNED → IN_PROGRESS → RESOLVED_PENDING_REVIEW → COMPLETED',
               existing_nullable=False)
    op.alter_column('issues', 'deadline_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Calculated: created_at + days_to_fix from AI extraction',
               existing_nullable=True)
    op.alter_column('issues', 'priority',
               existing_type=postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', name='priority_enum'),
               comment='low | medium | high — set by AI from urgency keywords',
               existing_nullable=False)
    op.alter_column('issues', 'description',
               existing_type=sa.TEXT(),
               comment='Detailed problem explanation from AI extraction',
               existing_nullable=False)
    op.alter_column('issues', 'title',
               existing_type=sa.VARCHAR(length=200),
               comment='Short problem description (AI-generated, max 50 chars preferred)',
               existing_nullable=False)
    op.alter_column('issues', 'raised_by_supervisor_id',
               existing_type=sa.INTEGER(),
               comment='Supervisor who reported the issue',
               existing_nullable=False)
    op.alter_column('issues', 'site_id',
               existing_type=sa.INTEGER(),
               comment='Which facility site the issue belongs to',
               existing_nullable=False)
    op.alter_column('issue_assignments', 'status',
               existing_type=postgresql.ENUM('ACTIVE', 'COMPLETED', 'REOPENED', name='assignment_status_enum'),
               comment='ACTIVE | COMPLETED | REOPENED',
               existing_nullable=False)
    op.alter_column('issue_assignments', 'due_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Copied from issues.deadline_at',
               existing_nullable=True)
    op.alter_column('issue_assignments', 'assigned_by_supervisor_id',
               existing_type=sa.INTEGER(),
               comment='Supervisor who assigned (or system user)',
               existing_nullable=False)
    op.alter_column('issue_assignments', 'assigned_to_solver_id',
               existing_type=sa.INTEGER(),
               comment='Problem solver who must fix it',
               existing_nullable=False)
    op.alter_column('issue_assignments', 'issue_id',
               existing_type=sa.INTEGER(),
               comment='Which issue is being assigned',
               existing_nullable=False)
    op.add_column('escalation_rules', sa.Column('issue_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('escalation_rules_issue_id_fkey'), 'escalation_rules', 'issues', ['issue_id'], ['id'])
    op.alter_column('escalation_rules', 'escalate_to_role',
               existing_type=sa.VARCHAR(length=50),
               comment='manager | supervisor | admin — who receives the alert',
               existing_nullable=False)
    op.alter_column('escalation_rules', 'max_time_without_response',
               existing_type=postgresql.INTERVAL(),
               comment="Time duration (e.g., '02:00:00') before escalation triggers",
               existing_nullable=False)
    op.alter_column('escalation_rules', 'max_call_attempts',
               existing_type=sa.INTEGER(),
               comment='Number of missed calls before escalation triggers',
               existing_nullable=False)
    op.alter_column('escalation_rules', 'priority',
               existing_type=postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', name='priority_enum'),
               comment='Which issue priority this rule applies to',
               existing_nullable=False)
    # ### end Alembic commands ###
