"""added call_sid to call_logs

Revision ID: d63b7483e782
Revises: aa3b7aa4a5d0
Create Date: 2026-03-11 16:14:45.450464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd63b7483e782'
down_revision: Union[str, Sequence[str], None] = 'aa3b7aa4a5d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('call_logs', sa.Column('call_sid', sa.String(length=64), nullable=True, comment='Twilio call SID — used by webhook to find the right log row'))
    op.create_index(op.f('ix_call_logs_call_sid'), 'call_logs', ['call_sid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_call_logs_call_sid'), table_name='call_logs')
    op.drop_column('call_logs', 'call_sid')
    # ### end Alembic commands ###
