"""
PURPOSE: Issue response schemas — READ ONLY.
─────────────────────────────────────────────
Issues are NEVER created through a form or direct API call.
They are ONLY created when the chatbot_service detects
a "create_issue" intent from the user's free text message.

These schemas are used to:
  - Format issue data in ChatResponse.data
  - Return issue details when user asks "show me issue 5"
  - Display issue lists when user asks "what are my open issues?"
  - Render issue cards in the dashboard

AIExtractionResult is used INTERNALLY by chatbot_service
when Groq AI parses the supervisor's natural language message.
It is NOT exposed to the user directly.

USED BY:
  - chatbot_service.py → AIExtractionResult (internal AI output)
  - chatbot_service.py → IssueResponse (query results in chat)
  - dashboard_service.py → IssueResponse (dashboard data)
  - GET /api/v1/issues/{id} → IssueDetailResponse (read-only)
  - GET /api/v1/issues → IssueListResponse (read-only)
"""

from pydantic import BaseModel, Field
from typing import Optional, List
from datetime import datetime
from decimal import Decimal
from app.core.enums import Priority, IssueStatus


# ══════════════════════════════════════════════════════════
# INTERNAL: AI Extraction — NOT exposed to users
# ══════════════════════════════════════════════════════════

class AIExtractionResult(BaseModel):
    """
    INTERNAL SCHEMA — used only by chatbot_service and ai_service.
    Never sent to or from the user directly.
    
    When supervisor types: "pipe broken in vepery site need to fix in 5 days"
    Groq AI (temperature=0) returns this structured data:
    
    {
        "problem_type": "plumbing",
        "location": "Vepery Site", 
        "days_to_fix": 5,
        "priority": "high",
        "title": "Pipe Leakage",
        "description": "Major leak in main supply pipe at Vepery site"
    }
    
    chatbot_service uses this to:
      1. Match site_id from location name
      2. Create Issue record
      3. Match solver by problem_type + site_id
      4. Create assignment
      5. Initiate Twilio call
    """
    problem_type: str = Field(
        ...,
        description=(
            "One of: plumbing, electrical, hvac, carpentry, "
            "painting, network, mechanical"
        ),
        examples=["plumbing"],
    )
    location: str = Field(
        ...,
        description="Extracted site name — fuzzy matched to sites table",
        examples=["Vepery Site"],
    )
    days_to_fix: int = Field(
        ...,
        ge=1,
        le=365,
        description="Number of days to fix — used to calculate deadline_at",
        examples=[5],
    )
    priority: Priority = Field(
        ...,
        description=(
            "Determined from urgency keywords in the message: "
            "urgent/emergency/asap → high, "
            "soon/important → medium, "
            "no urgency keywords → low"
        ),
        examples=["high"],
    )
    title: str = Field(
        ...,
        max_length=50,
        description="Short title generated by AI (max 50 chars)",
        examples=["Pipe Leakage"],
    )
    description: str = Field(
        ...,
        description="Detailed professional description generated by AI",
        examples=["Major leak in main supply pipe requiring immediate plumbing repair"],
    )


# ══════════════════════════════════════════════════════════
# RESPONSE: Issue data — returned in chat and dashboard
# ══════════════════════════════════════════════════════════

class IssueResponse(BaseModel):
    """
    Issue summary — used in list views and chat query responses.
    
    When user asks "what are my open issues?", the chatbot returns
    a list of these in ChatResponse.data.issues
    
    Also used by dashboard endpoints for aggregated views.
    """
    id: int
    site_id: int
    site_name: Optional[str] = Field(
        None,
        description="Resolved from sites table — human readable",
    )
    raised_by_supervisor_id: int
    supervisor_name: Optional[str] = None
    title: str
    description: str
    priority: Priority
    deadline_at: Optional[datetime] = None
    status: IssueStatus
    track_status: Optional[str] = Field(
        None,
        description="awaiting_solver | in_progress | awaiting_review | resolved",
    )
    latitude: Optional[Decimal] = None
    longitude: Optional[Decimal] = None
    created_at: datetime
    updated_at: datetime

    model_config = {"from_attributes": True}


class IssueImageBrief(BaseModel):
    """
    Nested image info inside IssueDetailResponse.
    Shows BEFORE and AFTER photos with AI verification status.
    """
    id: int
    image_url: str
    image_type: str = Field(
        ...,
        description="BEFORE (supervisor photo) or AFTER (solver photo)",
    )
    ai_flag: str = Field(
        ...,
        description="OK | SUSPECT | NOT_CHECKED — AI verification result",
    )
    uploaded_by_user_id: int
    uploader_name: Optional[str] = None
    created_at: datetime

    model_config = {"from_attributes": True}


class AssignmentBrief(BaseModel):
    """
    Nested assignment info inside IssueDetailResponse.
    Shows who is assigned and current status.
    """
    id: int
    assigned_to_solver_id: int
    solver_name: Optional[str] = None
    solver_phone: Optional[str] = None
    status: str = Field(
        ...,
        description="ACTIVE | COMPLETED | REOPENED",
    )
    due_date: Optional[datetime] = None
    total_call_attempts: Optional[int] = Field(
        None,
        description="How many Twilio calls made for this assignment",
    )
    last_call_status: Optional[str] = Field(
        None,
        description="INITIATED | MISSED | ANSWERED",
    )
    created_at: datetime

    model_config = {"from_attributes": True}


class IssueDetailResponse(BaseModel):
    """
    Full issue with nested images and assignments.
    
    Used when user asks "show me details of issue 5" in chat.
    Also used by GET /api/v1/issues/{id} read-only endpoint.
    
    Contains everything needed to render a full issue detail view:
      - Issue metadata (title, priority, status, deadline)
      - Site info (name, location, GPS)
      - All BEFORE and AFTER images
      - All assignments with call attempt history
    """
    id: int
    site_id: int
    site_name: Optional[str] = None
    site_location: Optional[str] = None
    raised_by_supervisor_id: int
    supervisor_name: Optional[str] = None
    title: str
    description: str
    priority: Priority
    deadline_at: Optional[datetime] = None
    status: IssueStatus
    track_status: Optional[str] = None
    latitude: Optional[Decimal] = None
    longitude: Optional[Decimal] = None
    images: List[IssueImageBrief] = Field(
        default_factory=list,
        description="All BEFORE and AFTER photos",
    )
    assignments: List[AssignmentBrief] = Field(
        default_factory=list,
        description="All assignments (may have multiple if reopened)",
    )
    complaints_count: Optional[int] = Field(
        None,
        description="Number of complaints filed for this issue",
    )
    created_at: datetime
    updated_at: datetime

    model_config = {"from_attributes": True}


class IssueListResponse(BaseModel):
    """
    Paginated issue list — used in chat query responses and dashboard.
    When user asks "what are my open issues?", this is embedded
    inside ChatResponse.data
    """
    total: int = Field(..., description="Total matching issues")
    issues: List[IssueResponse]
    page: int = Field(default=1)
    per_page: int = Field(default=20)