"""update db

Revision ID: 07943b427903
Revises: df09623f40b3
Create Date: 2026-04-03 21:37:17.901975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07943b427903'
down_revision: Union[str, Sequence[str], None] = 'df09623f40b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('call_logs', sa.Column('call_sid', sa.String(length=64), nullable=True, comment='Twilio call SID — used by webhook to find the right log row'))
    op.create_index('idx_call_logs_assignment_status_initiated', 'call_logs', ['assignment_id', 'status', 'initiated_at'], unique=False)
    op.create_index('idx_call_logs_call_sid', 'call_logs', ['call_sid'], unique=True, postgresql_where=sa.text('call_sid IS NOT NULL'))
    op.create_index(op.f('ix_call_logs_call_sid'), 'call_logs', ['call_sid'], unique=True)
    op.create_index('idx_chat_history_session_created', 'chat_history', ['session_id', sa.literal_column('created_at ASC')], unique=False)
    op.create_index('idx_user_active_updated_desc', 'chat_sessions', ['user_id', 'is_active', sa.literal_column('updated_at DESC')], unique=False)
    op.create_index('idx_complaints_supervisor', 'complaints', ['raised_by_supervisor_id'], unique=False)
    op.create_index('idx_escalations_assignment_id_resolved', 'escalations', ['assignment_id', 'resolved'], unique=False)
    op.create_index('idx_assignments_supervisor_status', 'issue_assignments', ['assigned_to_solver_id', 'status'], unique=False)
    op.create_index('idx_issue_history_issue_new_status', 'issue_history', ['issue_id', 'new_status'], unique=False)
    op.create_index('idx_issues_created_at', 'issues', ['created_at'], unique=False)
    op.create_index('idx_issues_site_status', 'issues', ['site_id', 'status'], unique=False)
    op.create_index('idx_issues_site_status_created', 'issues', ['site_id', 'status', 'created_at'], unique=False)
    op.create_index('idx_issues_status_deadline_at', 'issues', ['status', 'deadline_at'], unique=False)
    op.create_index('idx_issues_supervisor_status', 'issues', ['raised_by_supervisor_id', 'status'], unique=False)
    op.create_index(' idx_solver_skills_skill_site_available', 'problem_solver_skills', ['skill_type', 'site_id', 'is_available', sa.literal_column('priority DESC')], unique=False)
    op.create_index(' idx_solver_skills_solver_available', 'problem_solver_skills', ['solver_id', 'is_available'], unique=False)
    op.create_index('idx_users_is_active', 'users', ['is_active'], unique=False)
    op.create_index('idx_users_role_active', 'users', ['role', 'is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_users_role_active', table_name='users')
    op.drop_index('idx_users_is_active', table_name='users')
    op.drop_index(' idx_solver_skills_solver_available', table_name='problem_solver_skills')
    op.drop_index(' idx_solver_skills_skill_site_available', table_name='problem_solver_skills')
    op.drop_index('idx_issues_supervisor_status', table_name='issues')
    op.drop_index('idx_issues_status_deadline_at', table_name='issues')
    op.drop_index('idx_issues_site_status_created', table_name='issues')
    op.drop_index('idx_issues_site_status', table_name='issues')
    op.drop_index('idx_issues_created_at', table_name='issues')
    op.drop_index('idx_issue_history_issue_new_status', table_name='issue_history')
    op.drop_index('idx_assignments_supervisor_status', table_name='issue_assignments')
    op.drop_index('idx_escalations_assignment_id_resolved', table_name='escalations')
    op.drop_index('idx_complaints_supervisor', table_name='complaints')
    op.drop_index('idx_user_active_updated_desc', table_name='chat_sessions')
    op.drop_index('idx_chat_history_session_created', table_name='chat_history')
    op.drop_index(op.f('ix_call_logs_call_sid'), table_name='call_logs')
    op.drop_index('idx_call_logs_call_sid', table_name='call_logs', postgresql_where=sa.text('call_sid IS NOT NULL'))
    op.drop_index('idx_call_logs_assignment_status_initiated', table_name='call_logs')
    op.drop_column('call_logs', 'call_sid')
    # ### end Alembic commands ###
