"""initial schema

Revision ID: aa3b7aa4a5d0
Revises: 
Create Date: 2026-03-10 13:47:48.144521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aa3b7aa4a5d0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='Owner of this conversation session'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='Auto-generated from first user message'),
    sa.Column('issue_id', sa.Integer(), nullable=True, comment='If this session is about a specific issue'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='False = archived/deleted session'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chat_sessions_active', 'chat_sessions', ['is_active'], unique=False)
    op.create_index('idx_chat_sessions_updated', 'chat_sessions', ['updated_at'], unique=False)
    op.create_index('idx_chat_sessions_user', 'chat_sessions', ['user_id'], unique=False)
    op.add_column('chat_history', sa.Column('session_id', sa.Integer(), nullable=True, comment='Which conversation session this message belongs to'))
    op.create_foreign_key(None, 'chat_history', 'chat_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), server_default='', nullable=False, comment='Hashed password for authentication'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    op.drop_constraint(None, 'chat_history', type_='foreignkey')
    op.drop_column('chat_history', 'session_id')
    op.drop_index('idx_chat_sessions_user', table_name='chat_sessions')
    op.drop_index('idx_chat_sessions_updated', table_name='chat_sessions')
    op.drop_index('idx_chat_sessions_active', table_name='chat_sessions')
    op.drop_table('chat_sessions')
    # ### end Alembic commands ###
