"""
PURPOSE: Shapes notification responses and email request structures.
──────────────────────────────────────────────────────────────────────
USED BY:
  - GET  /api/v1/notifications           → NotificationResponse list
  - Internal: notification_service        → EmailNotificationRequest

COMMAND: Notifications are generated by:
  - Issue creation → supervisor confirmation
  - Solver assignment → solver notification
  - Escalation events → manager/supervisor email alerts
  - Complaint filed → solver notification
  - Deadline approaching → all stakeholders alerted
"""

from pydantic import BaseModel, Field
from typing import Optional, List
from datetime import datetime


# ── Internal: Email notification request ─────────────────
class EmailNotificationRequest(BaseModel):
    """
    Used internally by notification_service to send SMTP emails.
    Constructed during escalation events (Stage 4 and Stage 7).
    """
    to_emails: List[str] = Field(
        ...,
        description="Recipient email addresses",
    )
    subject: str = Field(
        ...,
        description="Email subject line",
    )
    body_html: str = Field(
        ...,
        description="HTML email body",
    )
    priority: str = Field(
        default="normal",
        description="Email priority: low, normal, high",
    )
    issue_id: Optional[int] = Field(
        None,
        description="Related issue ID for tracking",
    )
    escalation_id: Optional[int] = Field(
        None,
        description="Related escalation ID",
    )


# ── Response: In-app notification ────────────────────────
class NotificationResponse(BaseModel):
    """
    In-app notification shown in the user's notification panel.
    """
    id: int
    user_id: int
    title: str
    message: str
    notification_type: str = Field(
        ...,
        description="issue_created, solver_assigned, escalation, complaint, deadline_warning",
    )
    issue_id: Optional[int] = None
    is_read: bool = Field(default=False)
    created_at: datetime

    model_config = {"from_attributes": True}